spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hjb_blog?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: Hjb88619973.
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
server:
  port: 8089
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.hjb.blog.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  #path: /
  #file: school-blog.log
  level:
    com:
      hjb:
        blog:
          mapper: info

management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
      path: /
      threshold: 0